on:
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/main'  # Ensure the workflow runs only in the main branch
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Build and Load Docker image
      run: |
        docker build --load -t ecommercewebfrontend:latest ./client

    - name: Save Docker image
      run: |
        docker save ecommercewebfrontend:latest -o ecommercewebfrontend.tar
        pwd
        ls -lrt

    - name: Install Git LFS
      run: |
        git lfs install

    - name: Track Docker image tarball with LFS
      run: |
        git lfs track "ecommercewebfrontend.tar"

    - name: Configure Git
      run: |
        git config --global user.email "santhoshjayaram193@gmail.com"
        git config --global user.name "JayaramAkula"

    - name: Commit changes to TAR_FILE branch
      env:
        GITHUB_TOKEN: ${{ secrets.API_KEY }}
      run: |
        # Stage all changes, but we will unstage .gitattributes later
        git add .
        
        # Stash changes from main branch
        git stash
        
        # Fetch all branches
        git fetch origin
        
        # Switch to TAR_FILE branch
        git checkout TAR_FILE
        
        # Apply stashed changes
        git stash pop

        # Add the changes (including the new .gitattributes or any other files)
        git add .

        # Commit the changes
        git commit -m "Add Docker image tarball for ecommercewebfrontend:latest"

    - name: Push changes to TAR_FILE branch
      env:
        GITHUB_TOKEN: ${{ secrets.API_KEY }}
      run: |
        git push origin TAR_FILE
