on:
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/main'  # Ensure the workflow runs only in the main branch
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Build and Load Docker image
      run: |
        docker build --load -t ecommercewebfrontend:latest ./client

    - name: Save Docker image
      run: |
        docker save ecommercewebfrontend:latest -o ecommercewebfrontend.tar
        pwd
        ls -lrt

    - name: Install Git LFS
      run: |
        git lfs install

    - name: Track Docker image tarball with LFS
      run: |
        git lfs track "ecommercewebfrontend.tar"

    - name: Configure Git
      run: |
        git config --global user.email "santhoshjayaram193@gmail.com"
        git config --global user.name "JayaramAkula"

    - name: Add Docker image tarball
      env:
        GITHUB_TOKEN: ${{ secrets.API_KEY }}
      run: |
        git add .  # Stage all changes

    - name: Commit changes to TAR_FILE branch
      env:
        GITHUB_TOKEN: ${{ secrets.API_KEY }}
      run: |
        # Stash changes from main branch
        git stash push --keep-index
        
        # Switch to TAR_FILE branch
        git fetch origin
        if git rev-parse --verify origin/TAR_FILE; then
          git checkout TAR_FILE
          git pull origin TAR_FILE
        else
          git checkout -b TAR_FILE
        fi

        # Apply stashed changes and commit
        git stash apply
        git add .
        git commit -m "Add Docker image tarball for ecommercewebfrontend:latest"

    - name: Push changes to TAR_FILE branch
      env:
        GITHUB_TOKEN: ${{ secrets.API_KEY }}
      run: |
        git push origin TAR_FILE
