on:
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/main'  # Ensure the workflow runs only in the main branch
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.email "santhoshjayaram193@gmail.com"
        git config --global user.name "JayaramAkula"

    - name: Switch to TAR_FILE branch and clean files
      env:
        GITHUB_TOKEN: ${{ secrets.API_KEY }}
      run: |
        # Fetch the TAR_FILE branch
        git fetch origin
        
        # Check if the TAR_FILE branch exists on the remote
        if git rev-parse --verify origin/TAR_FILE; then
          git checkout TAR_FILE
          git pull
        else
          git checkout -b TAR_FILE  # Create a new TAR_FILE branch if it doesn't exist
        fi

        # Remove specific files if they exist
        rm -f .gitattributes ecommercewebbackend.tar
        
        # Stage and commit file deletions if needed
        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Remove existing .gitattributes and ecommercewebbackend.tar"
        fi
        
        # Push changes to the TAR_FILE branch
        git push origin TAR_FILE

    - name: Switch back to main branch
      run: |
        git checkout main

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Build and Load Docker image
      run: |
        docker build --load -t ecommercewebbackend:latest ./server

    - name: Save Docker image
      run: |
        docker save ecommercewebbackend:latest -o ecommercewebbackend.tar
        pwd
        ls -lrt

    - name: Install Git LFS
      run: |
        git lfs install

    - name: Track Docker image tarball with LFS
      run: |
        git lfs track "ecommercewebbackend.tar"

    - name: Stash changes and prepare for branch switch, Commit changes to TAR_FILE branch
      env:
        GITHUB_TOKEN: ${{ secrets.API_KEY }}
      run: |
        # Stage all changes, but we will unstage .gitattributes later
        git add .
        
        # Stash changes from main branch
        git stash
        
        # Switch to TAR_FILE branch
        git checkout TAR_FILE
        
        # Apply stashed changes
        git stash pop

        # Add the changes (including the new .gitattributes or any other files)
        git add .

        # Commit the changes
        git commit -m "Add Docker image tarball for ecommercewebbackend:latest"

    - name: Push changes to TAR_FILE branch
      env:
        GITHUB_TOKEN: ${{ secrets.API_KEY }}
      run: |
        git push origin TAR_FILE
