on:
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/main'  # Ensure the workflow runs only in the main branch
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Build and Load Docker image
      run: |
        docker build --load -t ecommercewebbackend:latest ./server

    - name: Save Docker image
      run: |
        docker save ecommercewebbackend:latest -o ecommercewebbackend.tar
        pwd
        ls -lrt

    - name: Install Git LFS
      run: |
        git lfs install

    - name: Track Docker image tarball with LFS
      run: |
        git lfs track "ecommercewebbackend.tar"

    - name: Configure Git
      run: |
        git config --global user.email "santhoshjayaram193@gmail.com"
        git config --global user.name "JayaramAkula"
        
    - name: Stash changes and prepare for branch switch
      run: |
        # Stage and stash all changes, including .gitattributes
        git add . 
        git stash

    - name: Commit changes to TAR_FILE branch
      env:
        GITHUB_TOKEN: ${{ secrets.API_KEY }}
      run: |
        # Fetch all branches from origin (to ensure TAR_FILE is available)
        git fetch --all
        
        # Check if the TAR_FILE branch exists on the remote
        if git rev-parse --verify origin/TAR_FILE; then
          git checkout TAR_FILE
          git pull origin TAR_FILE
        else
          git checkout -b TAR_FILE  # Create a new TAR_FILE branch if it doesn't exist
        fi

        # Apply stashed changes
        git stash apply

        # Resolve the conflict in .gitattributes manually
        # Choose the version of .gitattributes you want to keep (main's version or TAR_FILE's version)
        # Here, we will overwrite .gitattributes with the version from the `main` branch:
        git checkout main -- .gitattributes

        # Add all changes and commit
        git add .
        git commit -m "Add Docker image tarball for ecommercewebbackend:latest, resolved conflict in .gitattributes"

    - name: Push changes to TAR_FILE branch
      env:
        GITHUB_TOKEN: ${{ secrets.API_KEY }}
      run: |
        git push origin TAR_FILE
